# Generated by Django 3.2.6 on 2021-09-06 17:09

import activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20210906_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinfo',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to=activities.models.save_subject_image, verbose_name='Land certificate'),
        ),
    ]
